# Generated by Django 5.2.3 on 2025-06-23 04:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_no', models.CharField(max_length=20)),
                ('date_filled', models.DateField(auto_now_add=True)),
                ('branch', models.CharField(choices=[('Pimpalgaon', 'Pimpalgaon'), ('Ghatsila', 'Ghatsila'), ('Vidur', 'Vidur'), ('Vidhata', 'Vidhata')], max_length=20)),
                ('gender', models.CharField(choices=[('Groom', 'Groom'), ('Bride', 'Bride')], max_length=10)),
                ('caste', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('birth_place', models.CharField(max_length=100)),
                ('birth_time', models.TimeField()),
                ('birth_day', models.CharField(max_length=20)),
                ('nakshatra', models.CharField(max_length=100)),
                ('height_ft', models.IntegerField()),
                ('height_in', models.IntegerField()),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('color', models.CharField(max_length=50)),
                ('blood_group', models.CharField(max_length=5)),
                ('mother_tongue', models.CharField(max_length=50)),
                ('taluka', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('religion', models.CharField(max_length=50)),
                ('gotra', models.CharField(max_length=50)),
                ('kuldaivat', models.CharField(max_length=50)),
                ('deity', models.CharField(max_length=50)),
                ('subcaste', models.CharField(max_length=50)),
                ('education', models.CharField(max_length=100)),
                ('profession', models.CharField(max_length=100)),
                ('monthly_income', models.PositiveIntegerField()),
                ('job_address', models.TextField()),
                ('whatsapp_number', models.CharField(max_length=15)),
                ('phone_numbers', models.TextField(help_text='Comma-separated')),
                ('mother_alive', models.BooleanField()),
                ('father_alive', models.BooleanField()),
                ('brothers', models.PositiveIntegerField()),
                ('brothers_married', models.PositiveIntegerField()),
                ('sisters', models.PositiveIntegerField()),
                ('sisters_married', models.PositiveIntegerField()),
                ('raasi', models.CharField(max_length=100)),
                ('horoscope_nakshatra', models.CharField(max_length=100)),
                ('gan', models.CharField(max_length=100)),
                ('nadi', models.CharField(max_length=100)),
                ('charan', models.CharField(max_length=100)),
                ('horoscope_seen', models.BooleanField()),
                ('manglik_status', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Mild', 'Mild')], max_length=20)),
                ('parent_names', models.CharField(max_length=200)),
                ('mother_maiden_name', models.CharField(max_length=100)),
                ('mother_maiden_village', models.CharField(max_length=100)),
                ('preferred_marriage_type', models.CharField(choices=[('Mutual', 'Mutual understanding'), ('Registered', 'Registered'), ('Vedic', 'Vedic')], max_length=20)),
                ('residential_address', models.TextField()),
                ('other_info', models.TextField(blank=True)),
                ('image_1', models.ImageField(upload_to='profiles/')),
                ('image_2', models.ImageField(upload_to='profiles/')),
                ('image_3', models.ImageField(upload_to='profiles/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
