# Generated by Django 5.2.3 on 2025-06-23 14:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bureau', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='parent_names',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='phone_numbers',
        ),
        migrations.AddField(
            model_name='profile',
            name='declaration',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='declaration_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='profile',
            name='declaration_name',
            field=models.CharField(default='Not Provided', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='declaration_phone',
            field=models.CharField(default='0000000000', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='father_name',
            field=models.CharField(default='Not Provided', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='full_name',
            field=models.CharField(default='Not Provided', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='horoscope_file',
            field=models.FileField(blank=True, null=True, upload_to='horoscopes/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='mother_name',
            field=models.CharField(default='Not Provided', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_number_1',
            field=models.CharField(default='0000000000', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_number_2',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_number_3',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_number_4',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='profile',
            name='birth_day',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=5),
        ),
        migrations.AlterField(
            model_name='profile',
            name='brothers',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='brothers_married',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='charan',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='color',
            field=models.CharField(blank=True, choices=[('Fair', 'Fair'), ('Wheatish', 'Wheatish'), ('Dark', 'Dark')], max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='deity',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gan',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gotra',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='horoscope_nakshatra',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='horoscope_seen',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='job_address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='kuldaivat',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='manglik_status',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('Mild', 'Mild')], max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mother_maiden_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mother_maiden_village',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nadi',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nakshatra',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='preferred_marriage_type',
            field=models.CharField(choices=[('Mutual', 'Mutual understanding'), ('Registered', 'Registered'), ('Vedic', 'Traditional/Vedic')], max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='raasi',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='religion',
            field=models.CharField(choices=[('Hindu', 'Hindu'), ('Muslim', 'Muslim'), ('Christian', 'Christian'), ('Buddhist', 'Buddhist'), ('Jain', 'Jain'), ('Other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sisters',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sisters_married',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='subcaste',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
