# Generated by Django 5.2.3 on 2025-06-24 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bureau', '0002_remove_profile_parent_names_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='father_alive',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mother_alive',
            field=models.BooleanField(default=True),
        ),
    ]
