# Generated by Django 5.2.3 on 2025-06-26 04:30

import bureau.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bureau', '0003_alter_profile_father_alive_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image_1',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='image_2',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='image_3',
        ),
        migrations.AddField(
            model_name='profile',
            name='aadhar_image',
            field=models.ImageField(blank=True, null=True, upload_to='documents/', validators=[bureau.models.validate_image]),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='supporting_document',
            field=models.ImageField(blank=True, null=True, upload_to='documents/', validators=[bureau.models.validate_image]),
        ),
    ]
