# Generated by Django 5.2.3 on 2025-06-26 05:08

import bureau.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bureau', '0004_remove_profile_image_1_remove_profile_image_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/', validators=[bureau.models.validate_image]),
        ),
    ]
