# Generated by Django 5.2.3 on 2025-06-26 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bureau', '0005_alter_profile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='form_no',
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
    ]
